Filters
fscdev/vkwave pull request #62
Opened 2020-09-11 18:20 UTC by peach-lasagna

добавил comanlinefilter, который позволит парсить сообщение как аргументы командной строки

2020-09-13 11:28 UTC, prostomarkeloff commented
move to middlewares?

2020-09-13 11:28 UTC, peach-lasagna commented
saw

2020-09-14 10:54 UTC, peach-lasagna commented
@peach-lasagna @imexactlynotahuman

2020-09-14 11:56 UTC, prostomarkeloff requested changes

2020-09-14 11:56 UTC, prostomarkeloff commented on vkwave/bots/core/dispatching/dp/middleware/extension_middlewares.py
> +    >>> bot.add_middleware(clm)
`.add_middleware(clm())`

2020-09-14 11:56 UTC, prostomarkeloff commented on examples/bots/middleware_example.py
> +Как подключить мидлварь из встроенных:
Убрать из этого примера вообще. Перенести в `examples/bots/command_line_middleware_py`

2020-09-14 14:16 UTC, prostomarkeloff requested changes

2020-09-14 14:16 UTC, prostomarkeloff commented on examples/bots/middleware_example.py
> +    - не может передавать аргументы в мидлварь
Что это значит?

2020-09-14 14:16 UTC, prostomarkeloff commented on examples/bots/middleware_example.py
> +"""
Не надо писать комментарии в докстрингах. Их надо писать именно в "комментариях".

2020-09-14 15:00 UTC, prostomarkeloff requested changes
Все докстринги должны быть комментариями.

2020-09-15 11:28 UTC, merged